server:
  port: 8080

spring:
  sql:
    init:
      mode: never
  datasource:
    schema: schema.sql
    username: your_username
    password: your_password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        database: mysql
        format_sql: true 
    show-sql: false
    
  logging:
    level:
      root: debug
      sql: info

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Светлакова.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru

connection-to-site:
  user_agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com


